title: "Politically Math"
theme: "PaperMod"

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: Manifesto
          url: manifesto
          weight: 2
        - name: Ongoing Works
          url: ongoing-works
          weight: 3
        - name: About Us
          url: about-us
          weight: 4
        - name: Themes
          url: themes
          weight: 5
